# Generated by Django 3.1.3 on 2020-11-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20201114_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
